version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(APPVEYOR_REPO_COMMIT)
nuget:
  account_feed: true
  project_feed: true
before_build:
  - nuget restore src\
build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\autosetup.sln      # path to Visual Studio solution or project
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging