version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(APPVEYOR_REPO_COMMIT)
nuget:
  account_feed: true
  project_feed: true
build_script:
  - nuget restore src\
  - dotnet build src\autosetup\autosetup.csproj -c Release
  - dotnet pack src\autosetup\autosetup.csproj -o ..\..\AppOutput\autosetup -c Release
  - appveyor PushArtifact AppOutput\autosetup\autosetup*.nupkg
  - dotnet publish src\autosetup.vsix\autosetup.vsix.csproj --framework netcoreapp2.1  -o ..\..\AppOutput\autosetup.vsix -c Release