version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(APPVEYOR_REPO_COMMIT)
nuget:
  account_feed: true
  project_feed: true

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore src\
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
build_script:
  - dotnet build src\autosetup\autosetup.csproj -c Release
  - dotnet pack src\autosetup\autosetup.csproj -o ..\..\AppOutput -c Release
  - dotnet publish src\autosetup.vsix\autosetup.vsix.csproj --framework netcoreapp2.1  -o ..\..\AppOutput\autosetup.vsix -c Release
  
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
  - path: AppOutput\*.nupkg
    name: autosetupnugetpackage
after_build:
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
for:
-
  branches:
    only:
      - master
  deploy:
    provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: fHDidsWmxMYoUD8/IR+cXKIB/QyTZ9Rzw1W5d93Cf8a+UqRU65mUuIntARp1B/LD
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/